// <auto-generated />
using System;
using Infrastructure.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.EntityFramework.Migrations
{
    [DbContext(typeof(ContactsDbContext))]
    [Migration("20260421220837_SeedIdentityPasswords")]
    partial class SeedIdentityPasswords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.14");

            modelBuilder.Entity("ApplicationCore.Models.ContactAggregate.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasDiscriminator<string>("ContactType").HasValue("Contact");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Infrastructure.EntityFramework.Entities.CrmRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "6B4EE8AB-8BA8-4DDF-8E8E-CC0AF1D3AB10",
                            Description = "System administrator",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "6B4EE8AB-8BA8-4DDF-8E8E-CC0AF1D3AB11",
                            Description = "Sales manager",
                            Name = "SalesManager",
                            NormalizedName = "SALESMANAGER"
                        },
                        new
                        {
                            Id = "6B4EE8AB-8BA8-4DDF-8E8E-CC0AF1D3AB12",
                            Description = "Sales representative",
                            Name = "Salesperson",
                            NormalizedName = "SALESPERSON"
                        },
                        new
                        {
                            Id = "6B4EE8AB-8BA8-4DDF-8E8E-CC0AF1D3AB13",
                            Description = "Support employee",
                            Name = "SupportAgent",
                            NormalizedName = "SUPPORTAGENT"
                        },
                        new
                        {
                            Id = "6B4EE8AB-8BA8-4DDF-8E8E-CC0AF1D3AB14",
                            Description = "Read-only access",
                            Name = "ReadOnly",
                            NormalizedName = "READONLY"
                        });
                });

            modelBuilder.Entity("Infrastructure.EntityFramework.Entities.CrmUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "6D89BC32-15F1-4E30-AF25-53F1B4429A10",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CON-CRM-ADMIN-001",
                            CreatedAt = new DateTime(2026, 3, 31, 8, 0, 0, 0, DateTimeKind.Utc),
                            Department = "IT",
                            Email = "admin@wsei.edu.pl",
                            EmailConfirmed = true,
                            FirstName = "System",
                            FullName = "System Admin",
                            LastName = "Admin",
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN@WSEI.EDU.PL",
                            NormalizedUserName = "ADMIN@WSEI.EDU.PL",
                            PasswordHash = "AQAAAAIAAYagAAAAEIUGp/TT1NcVE8M77dDN1R49jG6hYMnAlyOzNFVZsFbxYLXF7djmW9FsFcIh1UyZ5A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "SEC-CRM-ADMIN-001",
                            Status = "Active",
                            TwoFactorEnabled = false,
                            UserName = "admin@wsei.edu.pl"
                        },
                        new
                        {
                            Id = "6D89BC32-15F1-4E30-AF25-53F1B4429A11",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "CON-CRM-SALES-001",
                            CreatedAt = new DateTime(2026, 3, 31, 8, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Sales",
                            Email = "sales@wsei.edu.pl",
                            EmailConfirmed = true,
                            FirstName = "Sales",
                            FullName = "Sales Manager",
                            LastName = "Manager",
                            LockoutEnabled = true,
                            NormalizedEmail = "SALES@WSEI.EDU.PL",
                            NormalizedUserName = "SALES@WSEI.EDU.PL",
                            PasswordHash = "AQAAAAIAAYagAAAAEMDVL814x0HYV8B6rILlR6sZjGfiS7H/0kQZNVMeYfsLd0pg/nFCQmr7/8zlW6NaEw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "SEC-CRM-SALES-001",
                            Status = "Active",
                            TwoFactorEnabled = false,
                            UserName = "sales@wsei.edu.pl"
                        });
                });

            modelBuilder.Entity("Infrastructure.Security.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefresTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "6D89BC32-15F1-4E30-AF25-53F1B4429A10",
                            RoleId = "6B4EE8AB-8BA8-4DDF-8E8E-CC0AF1D3AB10"
                        },
                        new
                        {
                            UserId = "6D89BC32-15F1-4E30-AF25-53F1B4429A11",
                            RoleId = "6B4EE8AB-8BA8-4DDF-8E8E-CC0AF1D3AB11"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ApplicationCore.Models.ContactAggregate.Company", b =>
                {
                    b.HasBaseType("ApplicationCore.Models.ContactAggregate.Contact");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nip")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasIndex("Nip")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("Company");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a8ecde7-0eaa-4e9e-a67f-3ac9857f4e11"),
                            CreatedAt = new DateTime(2026, 4, 20, 9, 30, 0, 0, DateTimeKind.Utc),
                            Email = "kontakt@balticsoft.pl",
                            Notes = "[{\"Content\":\"Klient strategiczny z Pomorza.\",\"CreatedAt\":\"2026-04-20T09:30:00Z\",\"Id\":\"8a8ecde7-0eaa-4e9e-a67f-3ac9857f5011\"}]",
                            Phone = "583221104",
                            Status = "Active",
                            Tags = "[\"b2b\",\"it\",\"partner\"]",
                            Name = "Baltic Soft Solutions",
                            Nip = "5842781123",
                            Website = "https://balticsoft.pl"
                        });
                });

            modelBuilder.Entity("ApplicationCore.Models.ContactAggregate.Organization", b =>
                {
                    b.HasBaseType("ApplicationCore.Models.ContactAggregate.Contact");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.ToTable("Contacts", t =>
                        {
                            t.Property("Name")
                                .HasColumnName("Organization_Name");
                        });

                    b.HasDiscriminator().HasValue("Organization");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a8ecde7-0eaa-4e9e-a67f-3ac9857f4e12"),
                            CreatedAt = new DateTime(2026, 4, 20, 9, 30, 0, 0, DateTimeKind.Utc),
                            Email = "biuro@izbacyfrowa.pl",
                            Notes = "[]",
                            Phone = "583004455",
                            Status = "Active",
                            Tags = "[\"networking\",\"wydarzenia\"]",
                            Description = "Siec wspolpracy firm technologicznych.",
                            Name = "Pomorska Izba Cyfrowa",
                            Type = "Other"
                        });
                });

            modelBuilder.Entity("ApplicationCore.Models.ContactAggregate.Person", b =>
                {
                    b.HasBaseType("ApplicationCore.Models.ContactAggregate.Contact");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("EmployerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasIndex("EmployerId");

                    b.HasIndex("OrganizationId");

                    b.HasDiscriminator().HasValue("Person");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a8ecde7-0eaa-4e9e-a67f-3ac9857f4e21"),
                            CreatedAt = new DateTime(2026, 4, 20, 9, 30, 0, 0, DateTimeKind.Utc),
                            Email = "k.witkowska@balticsoft.pl",
                            Notes = "[{\"Content\":\"Preferuje kontakt telefoniczny rano.\",\"CreatedAt\":\"2026-04-20T09:30:00Z\",\"Id\":\"8a8ecde7-0eaa-4e9e-a67f-3ac9857f6011\"}]",
                            Phone = "501778992",
                            Status = "Active",
                            Tags = "[\"decision-maker\",\"enterprise\"]",
                            BirthDate = new DateTime(1993, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployerId = new Guid("8a8ecde7-0eaa-4e9e-a67f-3ac9857f4e11"),
                            FirstName = "Katarzyna",
                            Gender = "Female",
                            LastName = "Witkowska",
                            OrganizationId = new Guid("8a8ecde7-0eaa-4e9e-a67f-3ac9857f4e12"),
                            Position = "Kierownik Projektu"
                        },
                        new
                        {
                            Id = new Guid("8a8ecde7-0eaa-4e9e-a67f-3ac9857f4e22"),
                            CreatedAt = new DateTime(2026, 4, 20, 9, 30, 0, 0, DateTimeKind.Utc),
                            Email = "m.czernecki@balticsoft.pl",
                            Notes = "[]",
                            Phone = "603115870",
                            Status = "Active",
                            Tags = "[\"security\",\"cloud\"]",
                            BirthDate = new DateTime(1990, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployerId = new Guid("8a8ecde7-0eaa-4e9e-a67f-3ac9857f4e11"),
                            FirstName = "Michal",
                            Gender = "Male",
                            LastName = "Czernecki",
                            OrganizationId = new Guid("8a8ecde7-0eaa-4e9e-a67f-3ac9857f4e12"),
                            Position = "Architekt Rozwiazan"
                        },
                        new
                        {
                            Id = new Guid("8a8ecde7-0eaa-4e9e-a67f-3ac9857f4e23"),
                            CreatedAt = new DateTime(2026, 4, 20, 9, 30, 0, 0, DateTimeKind.Utc),
                            Email = "a.golebiowska@izbacyfrowa.pl",
                            Notes = "[]",
                            Phone = "509447221",
                            Status = "Inactive",
                            Tags = "[\"events\",\"ngo\"]",
                            BirthDate = new DateTime(1988, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Agnieszka",
                            Gender = "Female",
                            LastName = "Golebiowska",
                            OrganizationId = new Guid("8a8ecde7-0eaa-4e9e-a67f-3ac9857f4e12"),
                            Position = "Koordynator Partnerstw"
                        });
                });

            modelBuilder.Entity("ApplicationCore.Models.ContactAggregate.Contact", b =>
                {
                    b.OwnsOne("ApplicationCore.Models.ContactAggregate.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("ContactId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("TEXT");

                            b1.HasKey("ContactId");

                            b1.ToTable("Contacts");

                            b1.WithOwner()
                                .HasForeignKey("ContactId");

                            b1.HasData(
                                new
                                {
                                    ContactId = new Guid("8a8ecde7-0eaa-4e9e-a67f-3ac9857f4e21"),
                                    City = "Gdansk",
                                    Country = "Polska",
                                    PostalCode = "80-244",
                                    Street = "ul. Grunwaldzka 103A",
                                    Type = "Work"
                                },
                                new
                                {
                                    ContactId = new Guid("8a8ecde7-0eaa-4e9e-a67f-3ac9857f4e22"),
                                    City = "Warszawa",
                                    Country = "Polska",
                                    PostalCode = "00-141",
                                    Street = "al. Jana Pawla II 28",
                                    Type = "Home"
                                },
                                new
                                {
                                    ContactId = new Guid("8a8ecde7-0eaa-4e9e-a67f-3ac9857f4e23"),
                                    City = "Lodz",
                                    Country = "Polska",
                                    PostalCode = "90-051",
                                    Street = "ul. Pilsudskiego 14",
                                    Type = "Work"
                                });
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Infrastructure.Security.RefreshToken", b =>
                {
                    b.HasOne("Infrastructure.EntityFramework.Entities.CrmUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Infrastructure.EntityFramework.Entities.CrmRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Infrastructure.EntityFramework.Entities.CrmUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Infrastructure.EntityFramework.Entities.CrmUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Infrastructure.EntityFramework.Entities.CrmRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.EntityFramework.Entities.CrmUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Infrastructure.EntityFramework.Entities.CrmUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApplicationCore.Models.ContactAggregate.Person", b =>
                {
                    b.HasOne("ApplicationCore.Models.ContactAggregate.Company", "Employer")
                        .WithMany("Employees")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ApplicationCore.Models.ContactAggregate.Organization", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employer");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ApplicationCore.Models.ContactAggregate.Company", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ApplicationCore.Models.ContactAggregate.Organization", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
