@WebApi_HostAddress = http://localhost:5058

### Pobierz wszystkie osoby
GET {{WebApi_HostAddress}}/api/contacts?page=1&size=20
Accept: application/json

###

### Pobierz osobę po id 
GET {{WebApi_HostAddress}}/api/contacts/3a4b5c6d-7e8f-9a0b-c1d2-e3f4g5h6i7j8
Accept: application/json

###

### Dodaj nową osobę (poprawne dane)
POST {{WebApi_HostAddress}}/api/contacts
Content-Type: application/json

{
  "firstName": "Michael",
  "lastName": "Clark",
  "email": "michael.clark@example.com",
  "phone": "+48 555 555 555",
  "gender": 0
}

###

### Dodaj nową osobę (brak nazwiska)
POST {{WebApi_HostAddress}}/api/contacts
Content-Type: application/json

{
  "firstName": "Emily",
  "lastName": "Taylor"
}

###

### Edytuj osobę 
PUT {{WebApi_HostAddress}}/api/contacts/3a4b5c6d-7e8f-9a0b-c1d2-e3f4g5h6i7j8
Content-Type: application/json

{
  "firstName": "Chris",
  "lastName": "Evans",
  "email": "chris.evans@example.com",
  "phone": "+48 444 444 444"
}

###

### Usuń osobę 
DELETE {{WebApi_HostAddress}}/api/contacts/aaf31a7c-d6c5-4c38-a845-dcbfdaf95af4

###

### Dodaj tag do osoby 
POST {{WebApi_HostAddress}}/api/contacts/25f35276-a294-4d9e-b431-812afca7ba65/tags
Content-Type: application/json

"vip"

###

### Dodaj notatkę do osoby 
POST {{WebApi_HostAddress}}/api/contacts/3d4f9239-3586-433a-bee0-a0858634f8f8/notes
Content-Type: application/json

{
  "content": "NOTENOTENTOE #1234"
}

###

### Pobierz notatki osoby
GET {{WebApi_HostAddress}}/api/contacts/3d4f9239-3586-433a-bee0-a0858634f8f8/notes
Accept: application/json
